### ISSUE TITLE
Amazing Project !! I seem to have some issues running it ...

### ISSUE THREAD

**Issue by animemandir** [hoangtien1005/animene#13]
What I did - 
- cloned repo
- changed repo name
- changed name in package.json, mnifest.json & index.html
- changed .env
- tired deploying it on vercel

# There were many warns in build logs.
### The deployment seems empty. [https://animezia.vercel.app/](https://animezia.vercel.app/)
![image](https://user-images.githubusercontent.com/78192713/161421664-b6b242c8-86d2-4aea-8590-b09b38ebe422.png)
![image](https://user-images.githubusercontent.com/78192713/161421673-128a67c4-9323-46ce-8d60-c72bb833e011.png)
![image](https://user-images.githubusercontent.com/78192713/161421687-4230c35e-a098-4b37-82da-aefc6e5e86d3.png)

**Comment by hoangtien1005** [comment]
Hi, I don't know if the name changing step is causing the problem or not, but you can try adding the environment variables of the project on Vercel:
Go to your project -> Settings -> Environment Variables and add these value


![Screen Shot 2022-04-03 at 5 18 16 PM](https://user-images.githubusercontent.com/80807888/161422845-764a02d7-cd36-4e9f-ab11-dae698a7a6d1.png)

**Comment by animemandir** [comment]
Ah thanks, fixed it. 
Btw, I tried using anilist api in normal js. Would like to discuss and learn about it more, can we talk on some social media? discord, fb, ig?
