### ISSUE TITLE
How to create a new page ?

### ISSUE THREAD

**Issue by animemandir** [hoangtien1005/animene#16]
So, I was wondering how do i create a new page ...where i can add any text or info like donate page, privacy policy, terms, etc.
I tried this - 
![image](https://user-images.githubusercontent.com/78192713/165971126-58fc2ad8-c1d3-4cb3-b2a8-898e6b12bf08.png)
so it was supposed to work at ./donate path..

**Comment by hoangtien1005** [comment]
you should also add the new route and the component in the `routes/index.js` file
